version: '3'

services:
  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: quicktmp
  redis:
    image: redis:7.0
    restart: always
  api:
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    restart: on-failure:10
    environment:
      - QUICKTMP_API_PORT=8080
      - QUICKTMP_SQL_DSN=root:12345@tcp(mysql:3306)/quicktmp?charset=utf8mb4&parseTime=True
      - QUICKTMP_REDIS_ADDR=redis:6379